name: Node.js CI and Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - run: npm ci
      - run: echo "Building the application..."
      - run: npm run build --if-present
      - run: echo "Running tests..."
      - run: npm test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - run: npm ci
      - run: echo "Running linting..."
      - run: npm run lint

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - run: npm ci
      - run: echo "Running security scan..."
      - run: npm run security-scan

  deploy:
    name: Deployment to Production
    runs-on: ubuntu-latest
    needs: [build-and-test, lint, security-scan]
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - run: echo "Installing Firebase Tools..."
      - run: npm install -g firebase-tools
      - run: npm ci
      - run: echo "Building the application..."
      - run: npm run build
      - run: echo "Deploying to Firebase Production..."
      - run: firebase deploy --project scrum-poket-453df --token ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SCRUM_POKET_453DF }}
